:version: 2.1.0
:ngAnnotateVersion: 0.15.4
= AngularJs Annotate Asset-Pipeline

image::https://codeship.com/projects/63e0e280-8c81-0132-c100-6e5f8c02ac8f/status?branch=master[link="https://codeship.com/projects/60472"]

The `angular-annotate-asset-pipeline` is an https://github.com/bertramdev/asset-pipeline-core[Asset Pipeline] module that provides annotations for dependecy injection to allow angular JavaScript or CofeeScript files to be minified in Gradle and Grails projects.

== Getting started

=== Gradle

[source,groovy,subs='attributes']
.build.gradle
----
buildscript {
    dependencies {
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.0.20"
        classpath "com.craigburke.angular:angular-annotate-asset-pipeline:{version}"
    }
}

dependencies {
	compile "com.craigburke.angular:angular-annotate-asset-pipeline:{version}"
}
----

Make sure the dependency is specified in both the buildscript and dependencies blocks.

=== Grails
Add the plugin to your **BuildConfig.groovy**:

[source,groovy,subs='attributes']
.BuildConfig.groovy
----
plugins {
	runtime ":angular-annotate-asset-pipeline:{version}"
}
----

== How it works

Since the parameter names are significant for AngularJS to do dependency injection and most minifiers rename parameters,
you have to use inline annotations. See https://docs.angularjs.org/tutorial/step_05[A Note on Minification]

This plugin uses https://github.com/olov/ng-annotate[ng-annotate v{ngAnnotateVersion}] to add those inline annotations and make your angular files safe to minify.

For example this

[source,javascript]
----
function IndexController($scope) {
	$scope.message = "Hello world";
};
----

Will be automatically annotated like so:

[source,javascript]
----
function IndexController($scope) {
	$scope.message = "Hello world";
};
IndexController.$inject = ["$scope"];
----
